export const LOAD_NOTIFICATION_LIST = 'LOAD_NOTIFICATION_LIST';
export const LOAD_NOTIFICATION_DETAIL = 'LOAD_NOTIFICATION_DETAIL';
export const CHECK_NOTIFICATION_UPDATE = 'CHECK_NOTIFICATION_UPDATE';
