export const LOAD_TEMPLATE_LIST = 'LOAD_TEMPLATE_LIST';
export const LOAD_TEMPLATE_DETAIL = 'LOAD_TEMPLATE_DETAIL';
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const LOAD_THUMBNAIL = 'LOAD_THUMBNAIL';
