export const LOAD_DATASOURCE_LIST = 'LOAD_DATASOURCE_LIST';
export const LOAD_DATASOURCE_DETAIL = 'LOAD_DATASOURCE_DETAIL';
export const UPDATE_DATASOURCE = 'UPDATE_DATASOURCE_DETAIL';
export const CREATE_DATASOURCE = 'CREATE_DATASOURCE_DETAIL';
