export const LOAD_REPORT_LIST = 'LOAD_REPORT_LIST';
export const LOAD_REPORT_DETAIL = 'LOAD_REPORT_DETAIL';
export const DELETE_REPORT = 'DELETE_REPORT';
export const CREATE_REPORT = 'CREATE_REPORT';
export const UPDATE_REPORT = 'UPDATE_REPORT';
