export const LOAD_COMMIT_DETAIL = 'LOAD_COMMIT_DETAIL';
export const CREATE_COMMIT = 'CREATE_COMMIT';
export const LOAD_COMMIT_LIST_BY_COMMITTER = 'LOAD_COMMIT_LIST_BY_COMMITTER';
export const LOAD_COMMIT_LIST_BY_FORM = 'LOAD_COMMIT_LIST_BY_FORM';
